name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Build
      uses: goreleaser/goreleaser-action@v2.1.1
      with:
        version: latest
        args: release --snapshot --skip-validate --skip-publish
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
