name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: test
        token: ${{ secrets.INTEGRATION_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Release
      uses: goreleaser/goreleaser-action@v2.1.1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.INTEGRATION_TOKEN }}
